---
# Copies the splunk forwarder script to remote server
- name: Splunk Forwarders Installation
  hosts: forwarders
  become: true
  
  tasks:
  - name: Copy file from local to remote server
    ansible.builtin.copy:
      src: /home/ansible-user/splunk-fwd.sh
      dest: /tmp/splunk-fwd.sh

  - name: Run the shell on remote server
    ansible.builtin.shell:
      cmd: sudo chmod +x /tmp/splunk-fwd.sh && /tmp/splunk-fwd.sh

# Configuring a Deployment Server
- name: Configure Splunk Deployment Server
  hosts: deployment_server
  become: true

  tasks:
  - name: Install Splunk Enterprise on remote server
    ansible.builtin.script: /home/ansible-user/splunk-install.sh
